# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 08:04
from __future__ import unicode_literals

from django.db import migrations, models


TALK_STATUS_PUBLISHED = 4


def set_published_status_for_published_talks(apps, schema_manager):
    Talk = apps.get_model("talk", "Talk")
    for talk in Talk.objects.filter(track_id__isnull=False):
        talk.status = TALK_STATUS_PUBLISHED
        talk.save()


class Migration(migrations.Migration):

    dependencies = [("talk", "0044_auto_20200310_2010")]

    operations = [
        migrations.AddField(
            model_name="talk",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Draft"),
                    (2, "Selected"),
                    (3, "Confirmed"),
                    (4, "Published"),
                ],
                default=1,
                verbose_name="Status",
            ),
        ),
        migrations.RunPython(set_published_status_for_published_talks),
    ]
